import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/navbar";
import { ToastContainer } from "react-toastify";
import SessionWraper from "./components/SessionWrappers";
import BottomNavBar from "./components/BottomNavBar";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-black h-screen w-screen`}
      >
        
        
        <ToastContainer theme="dark"/>
        <SessionWraper>
        <Navbar/>
        {children}
        <BottomNavBar/>
        </SessionWraper>
        
        
      </body>
    </html>
  );
}
